deploy:
  image: python:latest
  only:
    - master
  script:
    - pip install mkdocs-material
    - mkdocs build
    - apt-get update && apt-get install npm -y
    - npm install -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
  artifacts:
    paths:
      - site