deploy:
  image: python:3.8
  only:
    - master
  script:
    - pip install pipenv
    - pipenv install
    - pipenv run mkdocs build
    - apt-get update && apt-get install npm -y
    - npm install -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
  artifacts:
    paths:
      - site