site_name: Nyx Space
site_url: https://nyxspace.com
edit_uri: ""
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - navigation.footer
  logo: assets/logo-icon-inverted.png
  favicon: assets/favicon-256.png
  font:
    text: Montserrat
    code: Inconsolata
  palette:
    scheme: default
    primary: blue grey
    accent: orange

  icon:
    admonition:
      tip: material/rocket-launch-outline


nav:
  - Home: index.md
  - Nyx:
      - Examples:
          - Introduction: nyxspace/showcase/index.md
          - Mission design:
              - Table of contents: nyxspace/showcase/mission_design/index.md
              # - Lunar transfer [WIP]: nyxspace/showcase/mission_design/lunar_transfer.md
              - Orbit design from a genetic algorithm: nyxspace/showcase/mission_design/orbit_design_ga.md
          # - Constellation analysis [WIP]: nyxspace/showcase/constellation_analysis/index.md
          # - Spacecraft navigation:
          #     - Ground based navigation [WIP]: nyxspace/showcase/spacecraft_navigation/ground_nav.md
              # - CAPS [WIP]: nyxspace/showcase/spacecraft_navigation/CAPS.md
      # - User guide:
      #     - Getting started [WIP]: nyxspace/user_guide/start.md
      #     - Orbit definition and manipulation [WIP]: nyxspace/user_guide/orbits.md
      #     - Propagators and Monte Carlo runs [WIP]: nyxspace/user_guide/prop-mc.md
      #     - High fidelity models [WIP]: nyxspace/user_guide/hifimodels.md
      - MathSpec:
          - Introduction: nyxspace/MathSpec/index.md
          - Celestial:
              - Coordinate frames [WIP]: nyxspace/MathSpec/celestial/coord_systems.md
              # - Ephemeris [WIP]: nyxspace/MathSpec/celestial/ephemeris.md
              - Orbital elements: nyxspace/MathSpec/celestial/orbital_elements.md
              - Trajectory interpolation: nyxspace/MathSpec/celestial/interpolation.md
              - Eclipses: nyxspace/MathSpec/celestial/eclipse.md
              # - Events [WIP]: nyxspace/MathSpec/celestial/events.md
          - Dynamical Models:
              - Overview: nyxspace/MathSpec/models/overview.md
              - Gravity: nyxspace/MathSpec/models/gravity.md
              # - Spherical harmonics [WIP]: nyxspace/MathSpec/models/harmonics.md
              - Solar radiation pressure: nyxspace/MathSpec/models/srp.md
              # - Drag [WIP]: nyxspace/MathSpec/models/drag.md
              # - Control laws [WIP]: nyxspace/MathSpec/models/control_laws.md
              # - Finite burns [WIP]: nyxspace/MathSpec/models/finite_burns.md
          - Orbit determination:
              - Overview: nyxspace/MathSpec/orbit_determination/overview.md
              - Kalman filter: nyxspace/MathSpec/orbit_determination/kalman.md
              - State noise compensation: nyxspace/MathSpec/orbit_determination/snc.md
              - Smoothing: nyxspace/MathSpec/orbit_determination/smoothing.md
              - Iteration: nyxspace/MathSpec/orbit_determination/iteration.md
              - Measurement generation: nyxspace/MathSpec/orbit_determination/measurements.md
          - Monte Carlo:
              - Overview: nyxspace/MathSpec/monte_carlo/overview.md
              - Error modeling: nyxspace/MathSpec/monte_carlo/error_models.md
          - Optimization:
              - State transition matrix: nyxspace/MathSpec/optimization/stm.md
              - Targeting: nyxspace/MathSpec/optimization/targeting.md
              # - Multiple shooting [WIP]: nyxspace/MathSpec/optimization/multiple_shooting.md
              # - Optimizer [WIP]: nyxspace/MathSpec/optimization/panoc.md
          - Propagators: nyxspace/MathSpec/propagators.md
          - Appendices:
              - Dual numbers: nyxspace/MathSpec/appendix/dual_numbers.md
      - Versions: versions.md

  - Hifitime:
      - Hifitime: hifitime/index.md
      - Design: hifitime/design.md
      - Python user guide: hifitime/python.md
      - Rust user guide: hifitime/rust.md
      - Change Log: hifitime/changelog.md

  - ANISE:
      - ANISE: anise/index.md
      - Tutorials:
        - Tutorials index: anise/tutorials/index.md
        - Querying SPK files: anise/tutorials/Tutorial 01 - Querying SPK files.ipynb
        - Loading remote data: anise/tutorials/Tutorial 02 - Loading remote SPICE and ANISE files (meta almanac).ipynb
        - Working with Orbit class: anise/tutorials/Tutorial 03 - Defining and working with the Orbit structure.ipynb
        - Azimuth, Elevation, Range (AER): anise/tutorials/Tutorial 04 - Computing Azimuth Elevation and Range data.ipynb
        - Planetary constant kernels (PCK): anise/tutorials/Tutorial 05 - Using frame kernels and text planetary kernels.ipynb
        - Sun Probe Earth angle (SPE): anise/tutorials/Tutorial 06 - Sun probe Earth angle.ipynb
      - Explanation:
        - Explanation index: anise/explanation/index.md
        - Time management: anise/explanation/time.md
        - Validation: anise/explanation/validation.md
      - Reference:
        - Reference index: anise/reference/index.md
        - Python API:
          - ANISE Python: anise/reference/api/python/index.md
          - Astro: anise/reference/api/python/astro/index.md
          - Constants: anise/reference/api/python/astro/constants.md
          - Time: anise/reference/api/python/time.md
        - Rust API: anise/reference/api/rust/index.md
  
  - Pricing: pricing.md
  - Blog:
    - blog/index.md

extra_css:
  - stylesheets/extras.css

plugins:
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - blog
  - redirects:
      redirect_maps:
        'hifitime/intro.md': 'hifitime/index.md'
        'anise/intro.md': 'anise/index.md'

copyright: Copyright &copy; 2024 - Christopher Rabotin

repo_url: https://github.com/nyx-space/nyx
repo_name: nyx-space/nyx

extra:
  social:
    - icon: material/comment-multiple
      link: https://app.element.io/#/room/#astrodyn:matrix.org
      name: Astrodynamics on Matrix.org
    - icon: material/linkedin
      link: https://www.linkedin.com/in/chrisrabotin/
      name: Chris Rabotin on LinkedIn
    - icon: material/twitter
      link: https://twitter.com/CRabotin
      name: Chris Rabotin on Twitter
    - icon: material/email-outline
      link: mailto:christopher.rabotin@gmail.com
      name: Email me
  analytics:
    provider: google
    property: G-9Y2KY15FW5

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true


extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
