site_name: Nyx
theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
  logo: assets/logo-icon-inverted.png
  favicon: assets/favicon-256.png
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    scheme: default

nav:
  - Home: index.md
  - License: license.md
  - Examples:
    - Introduction: showcase/index.md
    - Mission design:
      - Table of contents: showcase/mission_design/index.md
      - Lunar transfer [WIP]: showcase/mission_design/lunar_transfer.md
      - Orbit design from a genetic algorithm: showcase/mission_design/orbit_design_ga.md
    - Constellation analysis [WIP]: showcase/constellation_analysis/index.md
    - Spacecraft navigation:
      - Ground based navigation [WIP]: showcase/spacecraft_navigation/ground_nav.md
      - CAPS [WIP]: showcase/spacecraft_navigation/CAPS.md
  - User guide:
    - Getting started [WIP]: user_guide/start.md
    - Orbit definition and manipulation [WIP]: user_guide/orbits.md
    - Propagators and Monte Carlo runs [WIP]: user_guide/prop-mc.md
    - High fidelity models [WIP]: user_guide/hifimodels.md
  - MathSpec:
    - Introduction: MathSpec/index.md
    - Time [WIP]: MathSpec/time.md
    - Celestial:
      - Coordinate frames [WIP]: MathSpec/celestial/coord_systems.md
      - Ephemeris [WIP]: MathSpec/celestial/ephemeris.md
      - Orbital elements [DONE]: MathSpec/celestial/orbital_elements.md
      - Trajectory interpolation [WIP]: MathSpec/celestial/interpolation.md
      - Eclipses [DONE]: MathSpec/celestial/eclipse.md
      - Events [WIP]: MathSpec/celestial/events.md
    - Acceleration and Force Models:
      - Overview [DONE]: MathSpec/models/overview.md
      - Gravity [DONE]: MathSpec/models/gravity.md
      - Spherical harmonics [WIP]: MathSpec/models/harmonics.md
      - Solar radiation pressure [DONE]: MathSpec/models/srp.md
      - Drag [WIP]: MathSpec/models/drag.md
      - Control laws [WIP]: MathSpec/models/control_laws.md
      - Finite burns [WIP]: MathSpec/models/finite_burns.md
    - Navigation [DONE]:
      - Overview: MathSpec/navigation/overview.md
      - Kalman filter: MathSpec/navigation/kalman.md
      - State noise compensation: MathSpec/navigation/snc.md
      - Smoothing: MathSpec/navigation/smoothing.md
      - Iteration: MathSpec/navigation/iteration.md
      - Measurement generation: MathSpec/navigation/measurements.md
    - Monte Carlo [WIP]:
      - Overview: MathSpec/monte_carlo/overview.md
      - Error modeling: MathSpec/monte_carlo/error_models.md
    - Optimization:
      - State transition matrix [DONE]: MathSpec/optimization/stm.md
      - Targeting: MathSpec/optimization/targeter.md
      - Multiple shooting: MathSpec/optimization/multiple_shooting.md
      - Optimizer: MathSpec/optimization/panoc.md
    - Propagators:
      - Runge Kutta: MathSpec/propagators/rk.md
      - Dormand Prince: MathSpec/propagators/prince.md
    - Appendices [DONE]:
      - Dual numbers: MathSpec/appendix/dual_numbers.md

  - Versions: versions.md

extra_css:
  - stylesheets/extras.css

plugins:
  - search

copyright: Copyright &copy; 2021 - Christopher Rabotin

repo_url: https://gitlab.com/nyx-space/nyx
repo_name: nyx-space/nyx

extra:
  social:
    - icon: material/blur
      link: https://www.svgbackgrounds.com
      name: Background licensed from SVGBackgrounds.com as CC BY 4.0. 
    - icon: material/comment-multiple
      link: https://app.element.io/#/room/#astrodyn:matrix.org
      name: Astrodynamics on Matrix.org
    - icon: material/linkedin
      link: https://www.linkedin.com/in/chrisrabotin/
      name: Chris Rabotin on LinkedIn
    - icon: material/twitter
      link: https://twitter.com/CRabotin
      name: Chris Rabotin on Twitter
    - icon: material/email-outline
      link: mailto:chris.rabotin@pm.me
      name: Email me

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - footnotes
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
